
[db]
host = "HOST"
port = "PORT"
db = "DB"
schema = "SCHEMA"
username = "USERNAME"
password = "PASSWORD"
# "postgresql://USERNAME:PASSWORD@IP:PORT/DB"

[redis]
host = "111.231.98.148"
port = 37255
username = ""
password = ""
db = 0
