
[db]
host = "HOST"
port = "PORT"
db = "DB"
schema = "SCHEMA"
username = "USERNAME"
password = "PASSWORD"
# "postgresql://USERNAME:PASSWORD@IP:PORT/DB"

[redis]
host = "localhost"
port = 6379
username = ""
password = ""
db = 0
