
[db]
host = "HOSTP"
port = "PORTP"
db = "DBP"
schema = "SCHEMAP"
username = "USERNAMEP"
password = "PASSWORDP"
# "postgresql://USERNAME:PASSWORD@IP:PORT/DB"

[redis]
host = "111.231.98.148"
port = 37255
username = ""
password = ""
db = 0
