
[db]
host = "HOSTP"
port = "PORTP"
db = "DBP"
schema = "SCHEMAP"
username = "USERNAMEP"
password = "PASSWORDP"
# "postgresql://USERNAME:PASSWORD@IP:PORT/DB"

[redis]
host = "localhost"
port = 6379
username = ""
password = ""
db = 0
